// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: parent.proto

package grpcs

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Parent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nullable   *wrappers.StringValue `protobuf:"bytes,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	CreateOnly string                `protobuf:"bytes,4,opt,name=create_only,json=createOnly,proto3" json:"create_only,omitempty"`
	Children   []*Child              `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Parent) Reset() {
	*x = Parent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parent) ProtoMessage() {}

func (x *Parent) ProtoReflect() protoreflect.Message {
	mi := &file_parent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parent.ProtoReflect.Descriptor instead.
func (*Parent) Descriptor() ([]byte, []int) {
	return file_parent_proto_rawDescGZIP(), []int{0}
}

func (x *Parent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Parent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parent) GetNullable() *wrappers.StringValue {
	if x != nil {
		return x.Nullable
	}
	return nil
}

func (x *Parent) GetCreateOnly() string {
	if x != nil {
		return x.CreateOnly
	}
	return ""
}

func (x *Parent) GetChildren() []*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

type ParentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *Parent `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ParentResponse) Reset() {
	*x = ParentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentResponse) ProtoMessage() {}

func (x *ParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentResponse.ProtoReflect.Descriptor instead.
func (*ParentResponse) Descriptor() ([]byte, []int) {
	return file_parent_proto_rawDescGZIP(), []int{1}
}

func (x *ParentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ParentResponse) GetData() *Parent {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ParentPaginatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []*Parent           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Meta *PaginationMetadata `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *ParentPaginatedResponse) Reset() {
	*x = ParentPaginatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParentPaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentPaginatedResponse) ProtoMessage() {}

func (x *ParentPaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentPaginatedResponse.ProtoReflect.Descriptor instead.
func (*ParentPaginatedResponse) Descriptor() ([]byte, []int) {
	return file_parent_proto_rawDescGZIP(), []int{2}
}

func (x *ParentPaginatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ParentPaginatedResponse) GetData() []*Parent {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParentPaginatedResponse) GetMeta() *PaginationMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_parent_proto protoreflect.FileDescriptor

var file_parent_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x67, 0x72, 0x70, 0x63, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x38, 0x0a, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x08, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x08,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x61, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7f, 0x0a, 0x17, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x32, 0xe8, 0x02, 0x0a, 0x07, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x5a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x12, 0x0f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x4a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x6a,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x34, 0x1a, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x5a,
	0x19, 0x32, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x49, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12,
	0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parent_proto_rawDescOnce sync.Once
	file_parent_proto_rawDescData = file_parent_proto_rawDesc
)

func file_parent_proto_rawDescGZIP() []byte {
	file_parent_proto_rawDescOnce.Do(func() {
		file_parent_proto_rawDescData = protoimpl.X.CompressGZIP(file_parent_proto_rawDescData)
	})
	return file_parent_proto_rawDescData
}

var file_parent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_parent_proto_goTypes = []interface{}{
	(*Parent)(nil),                  // 0: grpcs.Parent
	(*ParentResponse)(nil),          // 1: grpcs.ParentResponse
	(*ParentPaginatedResponse)(nil), // 2: grpcs.ParentPaginatedResponse
	(*wrappers.StringValue)(nil),    // 3: google.protobuf.StringValue
	(*Child)(nil),                   // 4: grpcs.Child
	(*PaginationMetadata)(nil),      // 5: grpcs.PaginationMetadata
	(*Pagination)(nil),              // 6: grpcs.Pagination
}
var file_parent_proto_depIdxs = []int32{
	3, // 0: grpcs.Parent.nullable:type_name -> google.protobuf.StringValue
	4, // 1: grpcs.Parent.children:type_name -> grpcs.Child
	0, // 2: grpcs.ParentResponse.data:type_name -> grpcs.Parent
	0, // 3: grpcs.ParentPaginatedResponse.data:type_name -> grpcs.Parent
	5, // 4: grpcs.ParentPaginatedResponse.meta:type_name -> grpcs.PaginationMetadata
	6, // 5: grpcs.Parents.GetPaginated:input_type -> grpcs.Pagination
	0, // 6: grpcs.Parents.Create:input_type -> grpcs.Parent
	0, // 7: grpcs.Parents.Update:input_type -> grpcs.Parent
	0, // 8: grpcs.Parents.Get:input_type -> grpcs.Parent
	2, // 9: grpcs.Parents.GetPaginated:output_type -> grpcs.ParentPaginatedResponse
	1, // 10: grpcs.Parents.Create:output_type -> grpcs.ParentResponse
	1, // 11: grpcs.Parents.Update:output_type -> grpcs.ParentResponse
	1, // 12: grpcs.Parents.Get:output_type -> grpcs.ParentResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_parent_proto_init() }
func file_parent_proto_init() {
	if File_parent_proto != nil {
		return
	}
	file_pagination_proto_init()
	file_child_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_parent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParentPaginatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parent_proto_goTypes,
		DependencyIndexes: file_parent_proto_depIdxs,
		MessageInfos:      file_parent_proto_msgTypes,
	}.Build()
	File_parent_proto = out.File
	file_parent_proto_rawDesc = nil
	file_parent_proto_goTypes = nil
	file_parent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParentsClient is the client API for Parents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParentsClient interface {
	GetPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*ParentPaginatedResponse, error)
	Create(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error)
	Update(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error)
	Get(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error)
}

type parentsClient struct {
	cc grpc.ClientConnInterface
}

func NewParentsClient(cc grpc.ClientConnInterface) ParentsClient {
	return &parentsClient{cc}
}

func (c *parentsClient) GetPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*ParentPaginatedResponse, error) {
	out := new(ParentPaginatedResponse)
	err := c.cc.Invoke(ctx, "/grpcs.Parents/GetPaginated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentsClient) Create(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error) {
	out := new(ParentResponse)
	err := c.cc.Invoke(ctx, "/grpcs.Parents/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentsClient) Update(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error) {
	out := new(ParentResponse)
	err := c.cc.Invoke(ctx, "/grpcs.Parents/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentsClient) Get(ctx context.Context, in *Parent, opts ...grpc.CallOption) (*ParentResponse, error) {
	out := new(ParentResponse)
	err := c.cc.Invoke(ctx, "/grpcs.Parents/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParentsServer is the server API for Parents service.
type ParentsServer interface {
	GetPaginated(context.Context, *Pagination) (*ParentPaginatedResponse, error)
	Create(context.Context, *Parent) (*ParentResponse, error)
	Update(context.Context, *Parent) (*ParentResponse, error)
	Get(context.Context, *Parent) (*ParentResponse, error)
}

// UnimplementedParentsServer can be embedded to have forward compatible implementations.
type UnimplementedParentsServer struct {
}

func (*UnimplementedParentsServer) GetPaginated(context.Context, *Pagination) (*ParentPaginatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaginated not implemented")
}
func (*UnimplementedParentsServer) Create(context.Context, *Parent) (*ParentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedParentsServer) Update(context.Context, *Parent) (*ParentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedParentsServer) Get(context.Context, *Parent) (*ParentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterParentsServer(s *grpc.Server, srv ParentsServer) {
	s.RegisterService(&_Parents_serviceDesc, srv)
}

func _Parents_GetPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentsServer).GetPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Parents/GetPaginated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentsServer).GetPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parents_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Parents/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentsServer).Create(ctx, req.(*Parent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parents_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Parents/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentsServer).Update(ctx, req.(*Parent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parents_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcs.Parents/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentsServer).Get(ctx, req.(*Parent))
	}
	return interceptor(ctx, in, info, handler)
}

var _Parents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcs.Parents",
	HandlerType: (*ParentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaginated",
			Handler:    _Parents_GetPaginated_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Parents_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Parents_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Parents_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parent.proto",
}
